server:
  port:
    8083

spring.devtools.livereload.enabled:
  true

spring.thymeleaf.cache:
  true

spring.datasource:
  name:
    auction_db
  driverClassName:
    org.h2.Driver
  url:
    jdbc:h2:mem:auction_db;DB_CLOSE_ON_EXIT=FALSE
  username:
    root
  password:
    root

spring.h2.console.enabled: true
spring.h2.console.path: /h2-console

spring:
  data:
    rest:
      base-path:
        /data-api
  jpa:
    show-sql:
      true
    hibernate:
      ddl-auto:
        update
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.H2Dialect
    open-in-view:
      true
  main:
    allow-bean-definition-overriding=true:
